export const calenderWeekDate=[
    {
        id:1,
        shortName:'Mo',
        fullName:'Montag',
        events:[
            {title:'Vue.js lernen',edit:false,color:'success'},
            {title:'üben,üben,üben',edit:false,color:'info'},
        ],
        active:false
    },
    {
        id:2,
        shortName:'Di',
        fullName:'Dienstag',
        events:[],
        active:false
    },
    {
        id:3,
        shortName:'Mi',
        fullName:'Mittwoch',
        events:[],
        active:true
    },
    {
        id:4,
        shortName:'Do',
        fullName:'Donnerstag',
        events:[
            {title:'Grillen mit Freunden',edit:false,color:'primary'},
            {title:'üben,üben,üben',edit:false,color:'info'},
        ],
        active:false
    },
    {
        id:5,
        shortName:'Fr',
        fullName:'Freitag',
        events:[],
        active:false
    },
    {
        id:6,
        shortName:'Sa',
        fullName:'Samstag',
        events:[],
        active:false
    },
    {
        id:7,
        shortName:'So',
        fullName:'Sonntag',
        events:[
            {title:'Müll rausbringen',edit:false,color:'danger'},
        ],
        active:false
    },
]